title: Just the Docs Test
description: A testsite for Jeykll for just-the-docs
theme: just-the-docs

url: https://tillik.github.io/justthedocstest

aux_links:
  Template Repository: https://github.com/tillik/justthedocstest
